version: "3.8"

services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile-dev-node
      args:
        USER_ID: ${CURRENT_USER_ID}
        GROUP_ID: ${CURRENT_GROUP_ID}
    ports:
      - 3000:3000
    volumes:
      - ./api:/usr/src/app
      - backend_home_npm:/home/node/.npm
    env_file: ./api/.env
    command: ["npm", "run", "dev"]

volumes:
  # persistent npm cache
  backend_home_npm:
