# https://github.com/marketplace/actions/build-and-push-docker-images#usage

name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      # Using checkout instead of Git Context so that we can use Path Context
      # because the Dockerfile resides in the ./api directory
      # and Git Context is not yet supported with subdirectories
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./api
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/integrate-github-api:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
